feat/DA-BE-22--CRUD-Wordlist
minhkycho18/DictionaryApp pull request #15
Opened 2023-10-03 10:39 UTC by HuynhLeDacTai

2023-10-03 14:33 UTC, minhkycho18 requested changes

2023-10-03 14:33 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/controller/WordListController.java
> +    @GetMapping
Giữa các biến với hàm cách ra 1 dòng a

2023-10-03 14:33 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/controller/WordListController.java
> +    private final WordListServiceImpl wordListService;
`private final WordlistService wordlistService` , tạo từ interface a

2023-10-03 14:33 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/controller/WordListController.java
> +    @PostMapping
Giữa các hàm cũng cách ra 1 dòng a

2023-10-03 14:33 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/controller/WordListController.java
> +    private String updateWordList(@PathVariable Long id){
Mấy hàm a đặt getMapping hay put j đó thì nên đặt public a
![image](https://github.com/minhkycho18/DictionaryApp/assets/80151408/e76fd278-fef0-4c4f-91b0-c2caad564d38)

2023-10-03 14:33 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/controller/WordListController.java
> +    private String updateWordList(@PathVariable Long id){
Sao lại có 2 hàm update luôn a, chỗ ni delete chứ

2023-10-03 14:33 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/controller/WordListController.java
> +        Objects.requireNonNull(wordList, "Word list should not be null");
Chỗ này a đừng xài cái này, xài Spring validation ấy a, validation cho từng field trong wordlist DTO, a nghiên cứu Spring validation thử, xài `@NotNull `,`@NotEmpty `các kiểu

2023-10-03 14:33 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/controller/WordListController.java
> +    private String createWordList(@RequestBody WordList wordList){
Chỗ requestBody a nên xài 1 cái DTO request wordlist j đó chỉ bao gồm những field cần để tạo 1 wordlist. VÌ xài luôn cái wordList entity thì có nhiều field k cần nhập sẽ bị null, k khuyến khích lắm a

2023-10-03 14:33 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/exception/ApiExceptionHandler.java
> +    @ExceptionHandler(value = {SQLIntegrityConstraintViolationException.class})
Giữa các hàm cách ra 1 dòng a hầy

2023-10-03 14:33 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/exception/ApiExceptionHandler.java
> +import org.hibernate.exception.ConstraintViolationException;
Thừa thư viện

2023-10-03 14:33 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/service/IWordLIstService.java
A đặt tên interface là WordListService, còn class là WordListServiceImpl luôn cho nó đồng bộ vs tui
Chữ I ở giữa còn viết Hoa kìa :)))

2023-10-03 14:33 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/service/WordListServiceImpl.java
> +    UserRepository userRepository;
giữa biến với hàm cách ra 1 dòng a

2023-10-03 14:33 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/service/WordListServiceImpl.java
> +    @Autowired
a dùng cái annotation `@RequiredArgsConstructor`  thay cho @Autowired sẽ đẹp code hơn, vì thg impl nó chỉ implements 1 cái service thôi
biến thì a để private final

2023-10-03 14:33 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/service/WordListServiceImpl.java
> +        User user = userRepository.findByEmail(wordList.getCreatedBy());
Chỗ này a xử lý thêm lỡ tìm k thấy email của user thì quăng ra exception j đó cho controller nó bắt

2023-10-03 14:33 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/service/WordListServiceImpl.java
> +    public void create(WordList wordList) {
đặt tên hàm nó ý nghĩa hơn a kiểu createWordList chẳng hạn

2023-10-03 14:33 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/service/WordListServiceImpl.java
> +        if(wordList.getTitle() == null || wordList.getTitle().isEmpty()){
Lỗi này a nên xài Spring validation bắt ngay trên controller luôn

2023-10-03 14:33 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/service/WordListServiceImpl.java
> +    public void delete(Long id) {
đặt tên hàm có ý nghĩa hơn

2023-10-03 14:33 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/service/WordListServiceImpl.java
> +            throw new EntityNotFoundException("WordList not found with ID: " + id);
Chỗ này a test trường hợp bị exception hn chạy có đúng k, nếu tui nhớ k lầm là ở Controller cũng phải throw cái exception này ra nữa thì nó mới bắt dc thì phải

2023-10-03 14:33 UTC, minhkycho18 commented on src/main/resources/application.properties
Đừng push file ni lên a, nếu như có config mới thì hẳn push, còn đổi pass thì đừng push

2023-10-03 14:33 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/service/WordListServiceImpl.java
> +        User user = userRepository.findByEmail(wordList.getCreatedBy());
Mà bình thường cái createBy này người ta đâu gửi thông qua request nhỉ, thường là lấy thông tin User thông qua token thì phải, chỗ ni a code tạm thôi pk

2023-10-03 14:33 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/service/WordListServiceImpl.java
> +        wordListRepository.save(WordList.builder()
Chỗ này lỡ bị trùng title thì sao a, tui nghĩ a nên xử lý ở đây luôn

2023-10-03 14:39 UTC, HuynhLeDacTai commented on src/main/java/com/pbl6/dictionaryappbe/controller/WordListController.java
> +    private final WordListServiceImpl wordListService;
oke anh

2023-10-03 14:39 UTC, HuynhLeDacTai commented on src/main/java/com/pbl6/dictionaryappbe/controller/WordListController.java
> +    @PostMapping
tại chỗ ni thằng intelij nó hiện cái no usage nên tui tưởng là nó cách rồi

2023-10-03 14:39 UTC, HuynhLeDacTai commented on src/main/java/com/pbl6/dictionaryappbe/controller/WordListController.java
> +        Objects.requireNonNull(wordList, "Word list should not be null");
ok

2023-10-03 14:40 UTC, HuynhLeDacTai commented on src/main/java/com/pbl6/dictionaryappbe/controller/WordListController.java
> +    private String updateWordList(@PathVariable Long id){
chắc ctrl z mà k để ý

2023-10-03 14:41 UTC, HuynhLeDacTai commented on src/main/java/com/pbl6/dictionaryappbe/service/WordListServiceImpl.java
> +        User user = userRepository.findByEmail(wordList.getCreatedBy());
ời chỗ ni tui làm tạm thôi

2023-10-04 10:32 UTC, minhkycho18 requested changes

2023-10-04 10:32 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/controller/WordListController.java
>          return "Add successfully";
Chỗ này tui nghĩ chắc nên trả ra thông tin Word list mới tạo luôn thì hay hơn hề

2023-10-04 10:32 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/dto/WordListDto.java
> +    @NotEmpty(message = "Title can not be empty")
A override lại hàm tui nhắn trên mes để custom lại cái message hầy

2023-10-04 10:32 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/dto/WordListDto.java
> +    private String createdBy;
Chỗ ni tui nghĩ cũng nên để NotEmpty

2023-10-04 10:32 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/service/WordListServiceImpl.java
> +        if (wordList.getTitle().isEmpty()) {
Chỗ ni check trên @Valid rồi k cần check đây nữa đâu a

2023-10-04 10:32 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/controller/WordListController.java
> +    public List<WordList> getWordlists() {
Chỗ ni trả về wordlist là nó lỗi ấy a, trong entity tui thấy a ignore cái user thôi, còn subcategory chưa có ignore, mà sau ni có category rồi trong category nó gọi đến vocabDefs đồ là nó bị vòng lặp ấy a. Nên 1 là a đánh ignore cái subcategory luôn, 2 là a viết 1 cái wordlistDtoResponse chỉ trả ra những thông tin cần thiết

2023-10-04 10:32 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/service/WordListServiceImpl.java
> +        wordListRepository.save(WordList.builder()
.

2023-10-04 10:34 UTC, minhkycho18 requested changes
Sửa xong mấy chỗ ni là ok r

2023-10-04 11:29 UTC, HuynhLeDacTai commented on src/main/java/com/pbl6/dictionaryappbe/controller/WordListController.java
> +    public List<WordList> getWordlists() {
Đoạn ni chưa làm tới caia subcategory nên chưa đánh á a

2023-10-04 11:29 UTC, HuynhLeDacTai commented on src/main/java/com/pbl6/dictionaryappbe/dto/WordListDto.java
> +    @NotEmpty(message = "Title can not be empty")
Oke a

2023-10-05 15:59 UTC, minhkycho18 approved these changes

2023-10-05 15:59 UTC, merged