DA-BE-29: CRUD Subcategory
minhkycho18/DictionaryApp pull request #34
Opened 2023-10-13 09:10 UTC by HuynhLeDacTai

2023-10-13 09:27 UTC, huybui2107 commented
Tốt lắm em ,cần cố gắng thêm

2023-10-13 09:46 UTC, HuynhLeDacTai commented
> Tốt lắm em ,cần cố gắng thêm

dạ cảm ơn sự góp ý của thầy :))

2023-10-13 14:16 UTC, minhkycho18 requested changes

2023-10-13 14:16 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/controller/SubcategoryController.java
> +    @GetMapping("/{id}")
chỗ này a coi lại, cái id này bên FE nhìn zô k biết là subcategory id hay wordlist id đâu, a nên đổi lại "/{wordlistId}".

2023-10-13 14:16 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/controller/SubcategoryController.java
> +        return subcategoryList.stream().map(subcategoryMapper::toSubcategoryDto).toList();
rg a k cho thg service hn trả lại List<SubcategoryDto> luôn đỡ phải map trên controller a

2023-10-13 14:16 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/dto/SubcategoryDto.java
> +
OCD lord: cho nó sát lên class đi a :)))

2023-10-13 14:16 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/controller/SubcategoryController.java
Cho thg service nó trả ra Dto luôn a, đỡ xử lý trên controller

2023-10-13 14:16 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/service/SubcategoryServiceImpl.java
> +    public List<Subcategory> getAllSubcategories(Long id) {
đặt tên param nó hàm ý lên a, wordlistId các kiểu

2023-10-13 14:16 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/dto/SubcategoryDto.java
Class này tui nghĩ a nên tách riêng làm 2 class là SubcategoryRequestDto vs subcategoryResponseDto( hoặc subcategoryDetailDtO) , đừng xài chung như này. Sau này muốn thay đổi cấu trúc response đồ khó lắm a. với lại lúc request có  nhiều field bị null

2023-10-13 14:16 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/mapper/WordListMapper.java
>      @Mapping(source = "createdAt", target = "createdAt")
bỏ cái này đi a

2023-10-13 14:16 UTC, minhkycho18 commented on src/main/java/com/pbl6/dictionaryappbe/service/SubcategoryServiceImpl.java
> +                .amountOfWord(0)
chỗ này tui nghĩ k cần set amount cũng dc, vì trong subcategory entity mình cho nó default = 0 r

2023-10-14 08:41 UTC, minhkycho18 approved these changes
좋아요

2023-10-14 08:45 UTC, merged